<table style=\"width: 100%; border: 1px solid #FFFFFF; border-collapse: collapse; cell-spacing: 0; cell-padding: 0\>
    <tr>
        <td style=\"text-align: center\" bgcolor="#00009C"><b><font color="#FFFFFF">
            .:: %HEADER% ::.</b><br />
        </td>
    </tr>
    <tr>
        <td style=\"text-align: left\">
            %CONTENT%
        </td>
    </tr>
    <tr>
        <td style=\"text-align: right\">
            Competition Ends %END%
        </td>
    </tr>
</table><br /><br />