<?
$event = array("




<table cellspacing=0 cellpadding=0 border=1 STYLE='border-collapse: collapse' bgcolor=#606060>
  <tr><td align=center colspan=2> %title% </td></tr>

  <tr><td align=left>Occured on %date% <td align=right> %elapsed% </td></tr>

  <tr><td align=left valign=top colspan=2> %event% </td></tr>

  <tr><td align=right colspan=2>Jump to event: %jump% </td></tr>

</table>




");
?>
