<?

include_once 'arena_module.inc';

include_once 'arena_tournament.inc';
include_once 'irca_tournament.inc';
include_once 'sarena_tournament.inc';

include_once 'ladder.inc';
include_once 'ladder_control.inc';
include_once 'ladder_details.inc';
include_once 'ladder_fighter.inc';
include_once 'ladder_location.inc';
include_once 'ladder_match.inc';
include_once 'ladder_stats.inc';
include_once 'ladder_type.inc';
include_once 'ladder_weapon_type.inc';

include_once 'overseer.inc';
include_once 'adjunct.inc';

include_once 'dojo_master.inc';
include_once 'registrar.inc';
include_once 'mission.inc';
include_once 'skipper.inc';
include_once 'steward.inc';
include_once 'commentator.inc';
include_once 'ranger.inc';

include_once 'irca.inc';
include_once 'irca_match.inc';
include_once 'irca_stats.inc';
include_once 'irca_control.inc';
include_once 'irca_details.inc';
include_once 'irca_fighter.inc';

include_once 'parse_npc.inc';
include_once 'npc_utilities.inc';

include_once 'survival.inc';
include_once 'survival_contract.inc';
include_once 'survival_creature.inc';
include_once 'survival_control.inc';
include_once 'survival_grade.inc';
include_once 'survival_hunter.inc';
include_once 'survival_type.inc';

include_once 'solo.inc';
include_once 'solo_comissioner.inc';
include_once 'solo_contract.inc';
include_once 'solo_control.inc';
include_once 'solo_grade.inc';
include_once 'solo_hunter.inc';
include_once 'solo_npc.inc';
include_once 'solo_type.inc';

include_once 'solo_lw.inc';
include_once 'solo_lw_contract.inc';
include_once 'solo_lw_control.inc';
include_once 'solo_lw_hunter.inc';
include_once 'solo_lw_npc.inc';

include_once 'starfield.inc';
include_once 'starfield_control.inc';
include_once 'starfield_details.inc';
include_once 'starfield_fighter.inc';
include_once 'starfield_location.inc';
include_once 'starfield_match.inc';
include_once 'starfield_restriction.inc';
include_once 'starfield_settings.inc';
include_once 'starfield_stats.inc';
include_once 'starfield_type.inc';

include_once 'twilight_gauntlet.inc';
include_once 'twilight_gauntlet_challenge.inc';

include_once 'tempestuous.inc';
include_once 'tempestuous_petition.inc';

include_once 'sheet_module.inc';
include_once 'skill.inc';
include_once 'field.inc';
include_once 'statribute.inc';
include_once 'character.inc';
include_once 'char.inc';

include_once 'article.inc';

include_once 'ro.inc';
include_once 'run_on_stats.inc';
include_once 'run_on.inc';
include_once 'run_on_hunter.inc';
include_once 'run_on_details.inc';

include_once 'poll.inc';
include_once 'option.inc';
include_once 'votes.inc';

?>