<?php

echo "<table style=\"border: 1px solid #000000; border-collapse: collapse; width: 75%\" cellspacing=\"0\" cellpadding=\"0\"><tr>";
echo "<td style=\"text-align: center; background-color: #00009C\"><p style=\"color: #FFFFFF; font-variant: small-caps\">.:: Archive Format Update ::.</p>";
echo "</td></tr>";

echo "<tr><td><p style=\"color: #000000\">";
echo "  The Fiction Archive Competitions are now open and the first competition is now running! You can get the details for the comp and open the submission option by clicking on the <a href=competition.php>Fiction Competition</a> link in the navigation module, or that link right there. Get to it! The comp ends January 31st, 2004! Credit Awards will be given out to the top scorers, and all who participate will receive monetary compensation as well. (That means you get paid for submitting something that you put SOME effort into).";
echo "</p></td></tr>";

echo "<tr><td style=\"text-align: right\">";
echo "Submitted by: <a href=\"mailto:Gravant@capncommonsense.com\">Ric Gravant</a>";
echo "</td></tr>";

echo "</table><br /><br />";

echo "<table style=\"border: 1px solid #000000; border-collapse: collapse; width: 75%\" cellspacing=\"0\" cellpadding=\"0\"><tr>";
echo "<td style=\"text-align: center; background-color: #00009C\"><p style=\"color: #FFFFFF; font-variant: small-caps\">.:: Archive Format Update ::.</p>";
echo "</td></tr>";

echo "<tr><td><p style=\"color: #000000\">";
echo "  Fixed the layout and style errors with the Archive that were reported. When Synthie recoded the script, he made a few syntax errors which leaded to a malformatted fiction readout. That, and the stats module block wasn't as long as it should have been. I fixed that too. :P I've also reordered the modules for the side, putting Navigation up top instead of below the posters list, which is now very long. Last update I made to the system is making it so when logged in, your Personal Library link will be in the navigation module.";
echo "</p></td></tr>";

echo "<tr><td style=\"text-align: right\">";
echo "Submitted by: <a href=\"mailto:Gravant@capncommonsense.com\">Ric Gravant</a>";
echo "</td></tr>";

echo "</table><br /><br />";

echo "<table style=\"border: 1px solid #000000; border-collapse: collapse; width: 75%\" cellspacing=\"0\" cellpadding=\"0\"><tr>";
echo "<td style=\"text-align: center; background-color: #00009C\"><p style=\"color: #FFFFFF; font-variant: small-caps\">.:: Fiction Archive Has Moved ::.</p>";
echo "</td></tr>";

echo "<tr><td><p style=\"color: #000000\">";
echo "  Yes, finally, the Fiction Archive is now at <a href=\"http://fiction.thebhg.org/\">http://fiction.thebhg.org/</a>. Blame Grav and his horrible coding that I had to fix for the delay. He must be stabbed continuously in the face. With a rusty iron pike.";
echo "</p></td></tr>";

echo "<tr><td style=\"text-align: right\">";
echo "Submitted by: <a href=\"mailto:synthparadox@thebhg.org\">SyNthetiC PaRadoX</a>";
echo "</td></tr>";

echo "</table><br /><br />";

echo "<table style=\"border: 1px solid #000000; border-collapse: collapse; width: 75%\" cellspacing=\"0\" cellpadding=\"0\"><tr>";
echo "<td style=\"text-align: center; background-color: #00009C\"><p style=\"color: #FFFFFF; font-variant: small-caps\">.:: Fiction Archive - Update ::.</p>";
echo "</td></tr>";

echo "<tr><td><p style=\"color: #000000\">";
echo "  Just an update, the Fiction Archive is now updated with the fictions from the old BHG Fiction Archive. The count is now sky high, which makes me a happy boy. Even if Jedi Jawa has some 4 stories now and is still disavowed. :P";
echo "</p></td></tr>";

echo "<tr><td style=\"text-align: right\">";
echo "Submitted by: <a href=\"mailto:Gravant@capncommonsense.com\">Ric Gravant</a>";
echo "</td></tr>";

echo "</table><br /><br />";

echo "<table style=\"border: 1px solid #000000; border-collapse: collapse; width: 75%\" cellspacing=\"0\" cellpadding=\"0\"><tr>";
echo "<td style=\"text-align: center; background-color: #00009C\"><p style=\"color: #FFFFFF; font-variant: small-caps\">.:: Fiction Archive ::.</p>";
echo "</td></tr>";

echo "<tr><td><p style=\"color: #000000\">";
echo "  G'day folks. The new fiction archive is up and running and awaiting the new domain at fiction.thebhg.org. Once that gets up, the Fiction Archive will move there for good. The site should be working fine, but should you come across a problem, let me know by eMailing me here: <a href=\"mailto:TheCapn@capncommonsense.com\">TheCapn@capncommonsense.com</a>. Have fun. <br /><br /> And don't break anything.";
echo "</p></td></tr>";

echo "<tr><td style=\"text-align: right\">";
echo "Submitted by: <a href=\"mailto:Gravant@capncommonsense.com\">Ric Gravant</a>";
echo "</td></tr>";

echo "</table>";

?>