<?php
	include_once 'header.php';
	    
	if (isset($_REQUEST[1])){
		$gui->setTitle ("SYWTBAP: Team Owner");
		
		$gui->addContent('<p>Team Ownership! Some would argue it\'s the most important aspect of Podracing. Then again, some would argue that drinking urine can grant absolution for your previous bad deeds. Take that as you will. At any rate, team ownership is not only important, it\'s crucial. Without team owners, there would be no teams. Without teams, there would be no Podracing. And that would be boring.');
		$gui->addContent('<p>So, the first thing you need to know how to do is start your team! To do this, click on the Options button <img src=images/options_button.jpg> which will take you to the admin section. Then simply click on the Create Team button <img src=images/create.png>.');
		$gui->addContent('<p>This will bring you to a simple form to fill out. If you can\'t figure out the form, I suggest that you don\'t create your own team. Your logo URL, website URL, and slogan are all optional, but I do suggest you at least have a slogan, as it makes you look more attractive as a team looking for members.');
		$gui->addContent('<p>Before we go on to team management, I should give you a brief overview of how a team works. Teams are composed of a Team Owner and Team Members. The Owner and Members donate their account credits into the Team Coffers. The Team Coffers are used for everything in Podracer, from registration fees to the actual purchase and modification of pods. This sport gets expensive, so its good to have a big bank roll or a lot of team members so your Team Coffers allow you to purchase items.');
		$gui->addContent('<p>The Team Owner is the only person who can purchase and modify pods, as well as sign them up in races. Additionally, the team member can also remove and promote members, as well as distribute credits to them from the Team Coffers. With that cleared up, lets move on.');
		$gui->addContent('Team Betting is different from Spectator Betting because of the addition of Race Vouchers. When you go to the betting page to place a bet, if you currently have any pods registered in any races, you will be issued a Race Voucher. You will get one Voucher for each pod you have entered in every pending race. Race vouchers are worth 1,000,000 credits for betting purposes!');
		$gui->addContent('<p align="center"><img src=images/manual/voucher.png></p>');
		$gui->addContent('If you click on "Use Voucher" you will follow the normal betting process outlined in the <a href=?1>Spectator</a> section, except that you have a pending 1 million credit line to start with. If you chose to use your voucher without any extra, put 0 in the amount box when picking your pod, and then click submit. The 5 million credit limit is till maintained, so the most you can bet on top of your voucher is 4 million. If you withdraw a voucher bet, 85% of anything above the 1 million voucher credit will be returned to your account. Lets move on.');	
		$gui->addContent('<p>Once you have your team created, return to the admin menu and you will see all the team management resources you could possibly imagine!');
		$gui->addContent('<p align="center"><img src= images/manual/options.png></p>');
		$gui->addContent('<p>I\'ll give you a walkthrough on some of the more complex ones later, and a brief overview of the simpler options now.');
		$gui->addContent('<p>Clicking on the Modify button <img src=images/modify_team.png> will allow you to edit your Team Name, Logo URL, Website URL, and Slogan. ');
		$gui->addContent('<p>Clicking on the Members button <img src=images/members.png> will allow you to promote another member to Team Leader and become a regular member of the team as well as deleting members from your team which you no longer want around for any reason.');
		$gui->addContent('<p>Click on the eMail button <img src=images/email_team.png> will bring you to a simple form which will allow you to send an eMail to all the members of your team. This is useful for getting information to all your members without needing mailing lists and such.');
		$gui->addContent('<p>Clicking on the Distribute button <img src=images/distribute.png> will give you the option of dealing out Team Funds to your Team Members. You select the team member from the dropdown box, enter the amount of credits you want to give them from the general coffers, and submit. Your team funds will be reduced by that amount, and the team members account credits will increase by that amount.');
		$gui->addContent('<p>Clicking on the Contribute button <img src=images/contribute.png> will allow you to add credits to the General Coffers. However many credits you enter into the field will be removed from your account balance and added to the Team Coffers. <b>This is the first and most crucial step you should take when starting a team!</b> Team Coffers are used for everything in Podracer, and your individual account balances don\'t matter as far as things within Podracer are concerned.');
		$gui->addContent('<p>Clicking on the Team button <img src=images/team.png> will allow you to toggle membership acceptance on and off. If your team is set to accept members, anyone can join your team. If your membership acceptance is off, nobody will be able to join your team. This is useful if you don\'t want new people on your already prime team, or if you need more new blood in the pool.');
		$gui->addContent('<p>Clicking on the Withdraw button <img src=images/withdraw.png> will allow you to withdraw your pod from a signed up race. This feature can be done via the Races menu as well. When you withdraw a pod, you get back 75% of your entry fee, and your registrations in the race are destroyed. ');
		$gui->addContent('<p>Clicking on the Disband button <img src=images/disband.png> will allow you to close your team. When you close your team, all your team assets are sold off (pods and modifications) and your liquidated assets are then evenly split between the current members of the team. This is an automatic split, so if you wish to pay back members differently, it is suggested you liquidate your own assets, distribute the credits manually, then disband the team.');
		$gui->addContent('<p>Those are the simple functions of team ownership. <a href=?pod>Continue to Pod Purchase/Modification</a>.');
		$gui->addContent('<hr /><p align="center">Learn About <a href=?2>Team Membership</a> | Learn About <a href=?3>Spectatorship</a><br /><br />');
	} elseif (isset($_REQUEST[pod])){	
		$gui->setTitle ("SYWTBAP: Pod Purchase/Modification");
		
		$gui->addContent('<p>Clicking on the Pods button <img src=images/pods.png> will allow you to sell and tweak your pods. However, this will be fairly useless to you at this point, as you don\'t own any pods! So, lets cover buying pods.');
		$gui->addContent('<p>First, you need to have credits in your Team Coffers. If you do, then your ready to buy pods and upgrade them. Click on the Junkyard button <img src=images/junkyard_button.jpg>.');
		$gui->addContent('<p>The first thing you will see in the Junkyard is two main menus. Pod Types and Mod Types. The first thing you need to purchase is a pod, so we\'ll start with Pod Types. ');
		$gui->addContent('<p>The pods are organized into categories which are fairly self explanatory. For this exercise, we\'ll go with a Stats Tradeoff pod. Pods in this category trade certain stats for other (i.e. high control [turning, traction, breaking] and low speed [acceleration, top speed]). The pod we will go with is the Farwan & Glott FG 8T8-Twin Block2 Special.');
		$gui->addContent('<p align="center"><img src=images/manual/pod.png></p>');
		$gui->addContent('<p>This is the pod we\'re looking at buying. This page displays everything you need to know about a pod. ');
		$gui->addContent('<p>The stats of the pod involve how the pod runs on the track. They may seem low when you look at some of the courses, which they are. Most pods need modifications to have any hope of surviving on the track. Given the stats of the pod, I think I have a plan in mind to tune it up into a race winner. So, I\'m going to buy the pod. This is accomplished by clicking on the link below the pod name, [Purchase This Pod]. The pod cost is 2,400,000 and there are an unlimited amount of these pods. Some pods, like special editions, have only a certain amount available, and will no longer be sold after that number reaches zero, so only the fastest will be able to snag these beauties. ');
		$gui->addContent('<p>Once we click the link, we\'ll be asked for our pod name. This is where you enter the name for your craft (which can be changed later). Once you have entered a name, submit the form. If you have enough credits in your Team Coffers to cover the cost of the pod, you\'ll be the owner of a brand-new Podracer! Congratulations!');
		$gui->addContent('<p>Now that you own your first pod, you will need to modify it. For this, click the Junkyard button in the menu again, and return to the Junkyard Menu.');
		$gui->addContent('<p>Now we will look at Modifications. Modifications, like pods, are broken down into categories. They are also fairly self explanatory. The only thing you need to know about modifications is that you can only install one modification "type" on a single pod. That means you can only install one part from the Acceleration category on a pod, along with one part from the Top Speed category, one from the Stability Upgrades and so forth.');
		$gui->addContent('<p>When browsing modifications, pay attention to the printout of their stats next to their name. For example, the Intake/Output Tuner (Traction -2, Turning -2, Acceleration +3, Top speed +3, Air brake -2, Repair +1), when installed on your pod, will do the following:');
		$gui->addContent('<br />Decrease the pod\'s traction by 2');
		$gui->addContent('<br />Decrease the pod\'s turning by 2');
		$gui->addContent('<br />Decrease the pod\'s air brake by 2');
		$gui->addContent('<br />Increase the pod\'s acceleration by 3');
		$gui->addContent('<br />Increase the pod\'s top speed by 3');
		$gui->addContent('<br />Increase the pod\'s repair by 1');
		$gui->addContent('<p>The best pods will have the right number of modifications altering their stats just right to give them a good balance of all stats. To keep track of how good your pod is, it is given a rating called an ASL, or Average Skill Level. The ASL of your pod is the sum of all the stats of your pod (It\'s acceleration + top speed + air brake + cooling + repair…). As a bonus, <b>All SEs will have a -10 ASL built in!</b> This means you get 10 extra modification points on your SE pods!'); 
		$gui->addContent('<p>Purchasing a modification is just as simple as purchasing a pod, however, instead of giving the modification a name, you chose which one of your team pods you wish to install it on from the dropdown list, and click submit. The mod will then be installed on said pod, and you\'ll be well on your way to becoming race-ready!');
		$gui->addContent('<p align="center"><img src=images/manual/mod.png></p>');
		$gui->addContent('<p>Now that you know how to purchase and modify your pods, we can return to the Options menu, and look at management of your pods. Clicking on Options and then Pods will bring you to a screen which looks like the following:');
		$gui->addContent('<p align="center"><img src=images/manual/teampods.png></p>');
		$gui->addContent('<p>If you click on the name of your pod, you will be able to view the current stats of your pod. If you click on Tweak, you will be brought to the Tweak menu, which will be covered soon. If you click on Edit, you will be able to change your pod\'s name and owner (should you trade it to another team and need to transfer it). If you click on Sell, you will sell your pod, along with all modifications, for 75% of the market value of both the pod and the modifications. These credits will be added back into the Team Coffers.');
		$gui->addContent('<p>Clicking on the name of one of the modifications listed below your pod will show you the information on the modification. If you click on the [Remove] link next to a modification, you will resell that modification to the junkyard for 75% of its market value.');
		$gui->addContent('<p>With that covered, we will move on to tweaks. Tweaks are small changes to your pod (adding engine wings, rewiring the controls, installing better cooling systems etc) that change the stats of your pod. Tweaks are free, and you may set and delete as many tweaks as you want for no cost as often as you want.');
		$gui->addContent('<p align="center"><img src= images/manual/tweak.png></p>');
		$gui->addContent('<p>Next to the name of each tweak is a dropdown box. From this box, you can select if you want to install the tweak, and, if applicable, what level of the tweak you wish to install. Next to the tweak level, you will see some stats along with +s and -s. Anything listed as +<stat> will slightly increase that stat, and anything listed as -<stat> will slightly reduce that stat.');
		$gui->addContent('<p>Depending on what kind of stats you want to change will determine what tweaks you want to activate. The stats which they modify are shorthand of their actual value names. The list is:');
		$gui->addContent('<br />Tr = Traction');
		$gui->addContent('<br />Tu = Turning');
		$gui->addContent('<br />Sp = Top Speed');
		$gui->addContent('<br />Ac = Acceleration');
		$gui->addContent('<br />Co = Cooling');
		$gui->addContent('<br />Re = Repair');
		$gui->addContent('<p>Once you\'ve run through your tweak menu, submit the changes, and your pod will be successfully tweaked.');
		$gui->addContent('<p>That\'s all there is to know about pods! <a href=?race>Continue to Race Registration</a>.');
		$gui->addContent('<hr /><p align="center">Learn About <a href=?2>Team Membership</a> | Learn About <a href=?3>Spectatorship</a><br /><br />');
	} elseif (isset($_REQUEST[race])){
		$gui->setTitle ("SYWTBAP: Race Management");
		
		$gui->addContent('<p>First, go to the Admin menu by clicking the options button. Then, click the Races button <img src=images/races.png>. This will bring you to the race management section.');
		$gui->addContent('<p align="center"><img src=images/manual/races.png></p>');
		$gui->addContent('<p>The screen you are looking at for the first time will not have anything listed under Race Registrations, which is fine. We will cover management of those later. For now, we will be concerned with Signups. In the dropdown menu, you will see all of the races which are currently available for registration, along with the Race\'s Average Skill Level. The Average Skill Level (ASL) of a race is a system designed to stagger the types of pods which can race in any given race.');
		$gui->addContent('<p>You will notice that each race has an ASL limit. Next to the pod\'s name in the dropdown box, you will notice it lists the pods ASL. If the pod you want to register for a race has an ASL equal to or less than the ASL Maximum, you may register it!');
		$gui->addContent('<p>The other race information you will see is Pod Limit and Buyin. Pod Limit is the total number of pods that can be in the race. If you want to register for a race with a small pod limit, you have to do it quickly, because space will fill up, and then you will not be able to register. ');
		$gui->addContent('<p>Additionally, to register for a race, you need to have enough credits in your Team Coffers to cover the Registration Fee. If you meet the ASL and Buyin requirements for the race, submit the form, and you will have a race registration!');
		$gui->addContent('<p>Now, as with any racing sport, you are able to modify your pod up until the race itself. If, during your modifications, your pod\'s ASL grows out of the acceptable range, you will be notified by a warning next to your pod. It is REQUIRED that your pod meet ASL requirements on the day of the race, or else your pod will be disqualified from the race and you will be fined! ');
		$gui->addContent('<p align="center"><img src=images/manual/invalid.png></p>');
		$gui->addContent('<p>If you see this warning next to your pod, it means that you have exceeded the ASL for the track! In this case, you must either remove your pod from the race, or modify the craft\'s stats. If it is beyond the registration close date, you WILL NOT BE ABLE TO WITHDRAW YOUR POD! In this case, you will need to delete modifications/retweak your pod to get the ASL below the track requirement or face a DQ and fine!');
		$gui->addContent('<p>If it is not before the race registration end date, simply withdraw your pod by clicking on the [Withdraw] link next to the pod name. If successful, you will no longer be registered for the race.');
		$gui->addContent('<p align="center"><img src=images/manual/withdraw.png></p>');
		$gui->addContent('<p>With that, if you\'ve read Pod Management and the Team Ownership section, you know all there is to know about managing a team! Congratulations, slugger! Now get out there and get racing!');
		$gui->addContent('<hr /><p align="center">Learn About <a href=?2>Team Membership</a> | Learn About <a href=?3>Spectatorship</a><br /><br />');
	} elseif (isset($_REQUEST[2])){	
		$gui->setTitle ("SYWTBAP: Team Member");
		
		$gui->addContent('Team Membership is the blood heart which keeps the blood (credits) flowing through the lumbering giants which are Podracer Teams. Team Members contribute credits to their team in exchange for race winnings and being able to tell women how much ass their team kicked on the track. But first, you\'ve gotta help out the team. Doing this is stupid simple. ');
		$gui->addContent('<p>First, you need to know how to join a team. To do this, click on the Options button <img src=images/options_button.jpg> which will take you to the admin section. Then simply click on the Join Team button <img src=images/members.png>.');
		$gui->addContent('<p>This will bring you to a page with a dropdown box of all the teams currently accepting new members. Find the team you want to join from the list, click the button, and you\'re now a team member!');
		$gui->addContent('<p>Before we go on to team membership, I should give you a brief overview of how a team works. Teams are composed of a Team Owner and Team Members. The Owner and Members donate their account credits into the Team Coffers. The Team Coffers are used for everything in Podracer, from registration fees to the actual purchase and modification of pods. This sport gets expensive, so its good to have a big bank roll or a lot of team members so your Team Coffers allow you to purchase items.');
		$gui->addContent('<p>The Team Owner is the only person who can purchase and modify pods, as well as sign them up in races. Additionally, the team member can also remove and promote members, as well as distribute credits to them from the Team Coffers. With that cleared up, lets move on.');
		$gui->addContent('Team Betting is different from Spectator Betting because of the addition of Race Vouchers. When you go to the betting page to place a bet, if you currently have any pods registered in any races, you will be issued a Race Voucher. You will get one Voucher for each pod you have entered in every pending race. Race vouchers are worth 1,000,000 credits for betting purposes!');
		$gui->addContent('<p align="center"><img src=images/manual/voucher.png></p>');
		$gui->addContent('If you click on "Use Voucher" you will follow the normal betting process outlined in the <a href=?1>Spectator</a> section, except that you have a pending 1 million credit line to start with. If you chose to use your voucher without any extra, put 0 in the amount box when picking your pod, and then click submit. The 5 million credit limit is till maintained, so the most you can bet on top of your voucher is 4 million. If you withdraw a voucher bet, 85% of anything above the 1 million voucher credit will be returned to your account. Lets move on.');	
		$gui->addContent('<p>Once you have joined a team, return to the admin menu and you will see all the options open to you and your fellow team members!');
		$gui->addContent('<p align="center"><img src= images/manual/member.png></p>');
		$gui->addContent('<p>I\'ll give you a brief overview of the functions now.');
		$gui->addContent('<p>Clicking on the Members button <img src=images/members.png> will allow you to view the other members of your team.');
		$gui->addContent('<p>Click on the Pods button <img src=images/pods.png> will allow you to view all the pods you currently own, along with their stats and modifications.');
		$gui->addContent('<p>Click on the Races button <img src=images/races.png> will allow you to view all the current races you are registered for, as well as link to you all your past race results.');
		$gui->addContent('<p>Click on the eMail button <img src=images/email_team.png> will bring you to a simple form which will allow you to send an eMail to all the members of your team. This is useful for getting information to all your members without needing mailing lists and such.');
		$gui->addContent('<p>Clicking on the Contribute button <img src=images/contribute.png> will allow you to add credits to the General Coffers. However many credits you enter into the field will be removed from your account balance and added to the Team Coffers. <b>This is the first and most crucial step you should take when joining a team!</b> Team Coffers are used for everything in Podracer, and your individual account balances don\'t matter as far as things within Podracer are concerned.');
		$gui->addContent('<p>Clicking on the Leave button <img src=images/leave.png> will allow you to quit a team. If/when you quit a team, you will not be refunded any of your donated credits, and your credit donation history for that team will be wiped clean. As far as the records go, you will not have existed in the team ever. This will allow you to join a new team, if you so desire, as well.');
		$gui->addContent('<hr /><p align="center">Learn About <a href=?1>Team Ownership</a> | Learn About <a href=?3>Spectatorship</a><br /><br />');
	} elseif (isset($_REQUEST[3])){
		$gui->setTitle ("SYWTBAP: Spectator");
		
		$gui->addContent('To be a Spectator means to do nothing with pods, but only with betting. This is the most likely position for people involved with Podracing to be. And its not because they can sneak onto the field, sniff gas, or shake hands with racers. Spectators care all about the credits!');
		$gui->addContent('<p>The spectator waits until all the registrations for a single race are in, then they go and place a bet on the pod they think will bend all the other pods over on the field! Once the registration deadline has past for a race, the betting begins. To check the registration deadlines for any given race, use the <a href="http://podracer.thebhg.org/calender.php">Calendar</a>. (<a href="http://podracer.thebhg.org/calender.php">http://podracer.thebhg.org/calender.php</a>). Your going to want to pay special attention to these dates on the calendar: ');
		$gui->addContent('<p align="center"><img src=images/manual/signup.png></p>');
		$gui->addContent('<p>These dates indicate that the signups for an event have closed. You can put your mouse over the text to see what race it is, and you can click the text for more information on the race, such as run date, odds, and other useful stuff!');
		$gui->addContent('<p align="center"><img src=images/manual/mouseover.png></p>');
		$gui->addContent('<p>Once the registration deadline for a race has past, it\'s time to lay your credits on the table! To do this, you simply have to go to the betting interface. Which is found by clicking the Betting button. <img src=images/manual/betting.png>. This will open up the betting interface and present the various options you, as a spectator have for betting!');
		$gui->addContent('<p align="center"><img src=images/manual/betscrn.png></p>');
		$gui->addContent('<p>Using the dropdown box, select your race from the list. When you have the race you want to bet on, click on the Bet Normally button. This will bring you to the next stage of betting, which is lying down your wager and choosing your winner.');
		$gui->addContent('<p align="center"><img src=images/manual/betscren.png></p>');
		$gui->addContent('<p>This time, you select your pod from the dropdown list. The first thing you see in the box is the pod odds. In this example, the pod Blazing Fire has been given house odds of 2.34. This means that for every 1 credit you spend, you get 2.34 back. So, in this instance, if I bet 2,500,000 credits on Blazing Fire, and Blazing Fire wins the race, I will get a total of 5,850,000 credits. If blazing fire loses, of course, I\'ll be getting nothing back, which is the risk of gambling. The last important thing to know before placing your bet is our house limit, which is 5,000,000 credits. Your bets cannot exceed this amount. If you enter more than this amount in the box, you will automatically be charged the house max of 5,000,000. ');
		$gui->addContent('<p>Now that you know what your betting on and for how much, click on the Submit button. You will see a confirmation page, telling you that you have bet successfully! Now, all you have to do is sit back and wait for race day. Once the Race Master begins the race, the laps will begin and your money will be up in the air. If your pod wins, you will automatically be credited your winnings by the system, so watch the Race Results page (http://podracer.thebhg.org/schedule.php?resl=show) on the day of a race to see the outcomes.');
		$gui->addContent('<p>Now, lets say that you change your mind and have a better feeling about a racer that was just tweaked by a different team. But oh noes! You already registered your bet! What are you to do? You can\'t make multiple bets for one race, so you\'ll need to retract your bet. Which, thankfully for you, Mr. Unprudent, is a very easy process!');
		$gui->addContent('<p>Click the betting button again, and you will see the same betting module. However, you will see something new, which is a list of all your pending bets, giving you the amount, the pod, and the race.');
		$gui->addContent('<p align="center"><img src=images/manual/betscreen.png></p>');
		$gui->addContent('<p>You will also see a link [Remove], which you can click to retract your bet. If you retract your bet, you will again be allowed to make bets on the pods, however, you will not get your full bet amount back. The Bookie Office has a 15% charge on your bets for retraction, so you will only get back 85% of your bet. However, if you will be able to change your bet to a pod you think you\'ll win, then the 15% loss is better than a 100% loss without gain, right? Am I right? Of course I am!');
		$gui->addContent('<p>Well, that\'s all you need to know to be a Podracing Spectator. May the races be good to you!');
		$gui->addContent('<hr /><p align="center">Learn About <a href=?1>Team Ownership</a> | Learn About <a href=?2>Team Membership</a><br /><br />');
	} else {
		$gui->addContent("<center><img src=images/manual/podracer_intro.jpg></center>");
		
		$gui->addContent('<p>So, you want to be a Podracer? Well congratulations! Reading this manual is the FIRST step to joining the elite ranks of those guys who race pods!<p>Now, you may be asking yourself, "Voice, I want to be come a Podracer, but I don\'t know where to start."<p>Well, by reading this manual, you\'re lying to me! You are already where you need to be to be a full-fledged Podracer! The first thing you need to do is figure out what role you want to play in Podracer.<p> We have 3 choices here in the Lyarna Circuit, and they are:');
		$gui->addContent('<br />1. <a href=?1>The Team Owner</a>');
		$gui->addContent('<br />2. <a href=?2>The Team Member</a>');
		$gui->addContent('<br />3. <a href=?3>The Spectator</a>');
		$gui->setTitle ("So, You want to be a Podracer!");
	}
	
	
	$gui->outputGui ();
?>