#!/bin/bash

BACKUPDIR="/var/backup"
LDAP_ROOT_DN="dc=perth,dc=optimiser,dc=com,dc=au"
SVN_REPOS="/home/svn/svn"
TRAC_REPOS="/home/svn/trac"

for arg in "$@"
do
	case "$arg" in
		mysql)
			echo
			echo Backing Up MySQL Databases...
			mkdir -p $BACKUPDIR/database
			chmod o-rwx $BACKUPDIR/database
			/usr/local/bin/backup-mysql $BACKUPDIR/database
			;;

		postgres|postgresql)
			echo
			echo Backing Up PostgreSQL Databases...
			mkdir -p $BACKUPDIR/database
			chmod o-rwx $BACKUPDIR/database
			/usr/local/bin/backup-postgresql $BACKUPDIR/database
			;;

		ldap)
			echo
			echo Backing Up LDAP Server...
			mkdir -p $BACKUPDIR/ldap
			chmod o-rwx $BACKUPDIR/ldap
			/usr/local/bin/backup-ldap $BACKUPDIR/ldap $LDAP_ROOT_DN
			;;

		subversion|svn)
			echo
			echo Backing Up Subversion Repository...
			mkdir -p $BACKUPDIR/subversion
			chmod o-rwx $BACKUPDIR/subversion
			for repos in `ls -1 --color=none $SVN_REPOS`
			do
				/usr/local/bin/backup-subversion $SVN_REPOS/$repos $BACKUPDIR/subversion
			done
			;;

		trac)
			echo
			echo Backing Up Trac Data Store...
			mkdir -p $BACKUPDIR/trac
			chmod o-rwx $BACKUPDIR/trac
			/usr/local/bin/backup-trac $BACKUPDIR/trac $TRAC_REPOS
			;;

		*)
			echo
			echo "Got unknown parameter: $arg"
			;;
	esac
done

echo Removing old backups...
for DIR in ${BACKUPDIR}/database ${BACKUPDIR}/subversion ${BACKUPDIR}/trac ${BACKUPDIR}/webmin;
do
	echo ${DIR}
	COUNT=0
	for FILE in `ls -r1 ${DIR}`;
	do
		COUNT=$((${COUNT} + 1))
		if [[ ${COUNT} -gt 30 ]]; then
			echo " - Removing ${DIR}/${FILE}"
			rm -rf ${DIR}/${FILE}
		fi
	done
done
#for OLD in `find $BACKUPDIR -mtime +30 -type d`;
#do
#	if [[ -e $OLD ]]; then
#		echo " - Removing $OLD"
#		rm -rf $OLD
#	fi
#done
