#!/bin/bash

SVN="/usr/bin/svn"

if [[ $# -eq 0 ]]; then
  echo "You must specify at least one of the following sites to update:"
  echo " roster          Roster Objects and Utilities"
	echo " bugs            Bug Tracker"
  echo " calypso         BHG Blogs"
	echo " citadel         Citadel"
  echo " holonet         Main Holonet Site"
  echo " holonet-devel   Development and testing Holonet Site"
	echo " ircstats        IRC Stats (Hermit)"
	echo " ka              Kabal Authority"
  echo " ka-devel        Kabal Authority Development"
	echo " mall            Mall"
	echo " mybhg           MyBHG - Main Website"
	echo " mybhg-devel     MyBHG - Testing"
	echo " tactician       Tactician Website"
fi

for site in $*; do
	case $site in
		roster)
			echo Updating Roster...
			pushd /home/virtual/thebhg.org/usr/share/roster3/include > /dev/null
			$SVN update
			popd > /dev/null
			pushd /var/www/html/util > /dev/null
			$SVN update
			popd > /dev/null
			;;

		bugs)
			echo Updating Bug Tracker...
			pushd /home/virtual/thebhg.org/home/bugs/public_html > /dev/null
			$SVN update
			chown -R 22096:admin5 .
			popd > /dev/null
			;;

		holonet)
			echo Updating Holonet...
			pushd /home/virtual/thebhg.org/home/holonet/public_html > /dev/null
			$SVN update
			chown -R 22110:admin5 .
			popd > /dev/null
			;;

		holonet-devel)
			echo Updating Holonet Devel Site...
			pushd /home/virtual/thebhg.org/var/www/holonet-devel > /dev/null
			$SVN update
			chown -R admin5:admin5 .
			popd > /dev/null
			;;

		mybhg)
		  echo Updating MyBHG...
			pushd /home/virtual/thebhg.org/var/www/html > /dev/null
			$SVN update
			chown -R admin5:admin5 .
			popd > /dev/null
			;;

		mybhg-devel)
			echo Updating MyBHG Development...
			pushd /home/virtual/thebhg.org/home/my/public_html > /dev/null
			$SVN update
			chown -R 22129:admin5 .
			popd > /dev/null
			;;

		tactician)
			echo Updating Tactician Website...
			pushd /home/virtual/thebhg.org/home/tactician/public_html > /dev/null
			$SVN update
			chown -R 22109:admin5 .
			popd > /dev/null
			;;

		calypso)
			echo Updating Calypso...
			pushd /home/virtual/thebhg.org/home/blogs/public_html > /dev/null
			$SVN update
			chown -R 22120:admin5 .
			popd > /dev/null
			;;

		ka)
			echo Updating Kabal Authority...
			pushd /home/virtual/thebhg.org/home/ka/public_html > /dev/null
			$SVN update
			chown -R 22130:admin5 .
			popd > /dev/null
			;;

		ka-devel)
			echo Updating Kabal Authority Development...
			pushd /home/virtual/thebhg.org/home/katest/public_html > /dev/null
			$SVN update
			chown -R 22135:admin5 .
			popd > /dev/null
			;;

		mall)
			echo Updating Mall...
			pushd /home/virtual/thebhg.org/home/mall/public_html > /dev/null
			$SVN update
			chown -R 22136:admin5 .
			popd > /dev/null
			;;

		citadel)
			echo Updating Citadel...
			pushd /home/virtual/thebhg.org/home/citadel/public_html > /dev/null
			$SVN update
			chown -R 22117:admin5 .
			popd > /dev/null
			;;

		ircstats)
			echo Updating IRC Stats...
			pushd /home/virtual/anya/var/www/html > /dev/null
			$SVN update
			chown -R anya:admin5 .
			popd > /dev/null
			;;

	esac
done

