#!/bin/bash

SVN="/usr/bin/svn"

if [[ $# -eq 0 ]]; then
	echo "You must specify at least one of the following sites to update:"
	echo " roster          Roster Objects and Utilities"
	echo " roster-devel    Roster Devel Objects and Utilities"
	echo " boards          Message Boards Production Site"
	echo " boards-devel    Message Boards Development Site"
	echo " calypso         BHG Blogs"
	echo " citadel         Citadel"
	echo " holonet         Main Holonet Site"
	echo " holonet3-devel  Development and testing Holonet Site"
	echo " holonet4-devel  Development and testing Holonet 4 Site"
	echo " ircstats        IRC Stats (Hermit)"
	echo " ka              Kabal Authority"
	echo " ka-devel        Kabal Authority Development"
	echo " lyarna          Lyarna"
	echo " lyarna-devel    Lyarna Development"
	echo " mybhg           MyBHG - Main Website"
	echo " mybhg-devel     MyBHG - Testing"
	echo " roster4         Roster 4 Objects and Utilities"
	echo " scum            Scum - Main site"
	echo " scum-devel      Scum - Testing"
	echo " tactician       Tactician Website"
	echo " tactician-devel Tactician Development Website"
fi

for site in $*; do
	case $site in
		webmin)
			echo "Select module to update:"
			echo "citadel"
			echo "holonet"
			echo "holonet3-devel"
			echo "holonet4-devel"
			echo "ka"
			echo "ka-devel"
			echo "lyarna"
			echo "lyarna-devel"
			echo "scum"
			echo "scum-devel"
			echo "tactician"
			echo "tactician-devel"
			exit 0
			;;

		roster)
			echo Updating Roster...
			pushd /usr/share/roster > /dev/null
			$SVN update
			popd > /dev/null
			pushd /root/util > /dev/null
			$SVN update
			popd > /dev/null
			;;

		roster-devel)
			echo Updating Roster Devel...
			pushd /home/bhgdevel/usr/share/roster > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		boards)
			echo Updating Boards...
			pushd /home/boards/public_html > /dev/null
			$SVN update
			chown -R boards:boards .
			popd > /dev/null
			;;

		boards-devel)
			echo Updating Boards Devel...
			pushd /home/bhgdevel/domains/boards.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		calypso)
			echo Updating Calypso...
			pushd /home/thebhg/domains/blogs.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		citadel)
			echo Updating Citadel...
			pushd /home/thebhg/domains/citadel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		holonet)
			echo Updating Holonet...
			pushd /home/thebhg/domains/holonet.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		holonet3-devel)
			echo Updating Holonet Devel Site...
			pushd /home/bhgdevel/domains/holonet3.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		holonet4-devel)
			echo Updating Holonet Devel Site...
			pushd /home/bhgdevel/domains/holonet.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		ircstats)
			echo Updating IRC Stats...
			pushd /home/thebhg/domains/ircstats.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		ka)
			echo Updating Kabal Authority...
			pushd /home/ka/public_html > /dev/null
			$SVN update
			chown -R ka:ka .
			chmod -R go+r .
			popd > /dev/null
			;;

		ka-devel)
			echo Updating Kabal Authority Development...
			pushd /home/bhgdevel/domains/ka.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		lyarna)
			echo Updating Lyarna...
			pushd /home/thebhg/domains/lyarna.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		lyarna-devel)
			echo Updating Lyarna Development...
			pushd /home/bhgdevel/domains/lyarna.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		mybhg)
			echo Updating MyBHG...
			pushd /home/thebhg/domains/www.mybhg.org/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		mybhg-devel)
			echo Updating MyBHG Development...
			pushd /home/bhgdevel/domains/mybhg.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		roster4)
			echo Updating Roster 4...
			pushd /usr/share/bhg > /dev/null
			$SVN update
			popd > /dev/null
			;;

		scum)
		  echo Updating Scum...
			pushd /home/thebhg/public_html > /dev/null
			$SVN update
			chown -R thebhg:thebhg .
			popd > /dev/null
			;;

		scum-devel)
			echo Updating Scum Development...
			pushd /home/bhgdevel/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

		tactician)
			echo Updating Tactician Website...
			pushd /home/tactician/public_html > /dev/null
			$SVN update
			chown -R tactician:tactician .
			popd > /dev/null
			;;

		tactician-devel)
			echo Updating Tactician Development...
			pushd /home/bhgdevel/domains/tactician.devel.thebhg.org/public_html > /dev/null
			$SVN update
			chown -R bhgdevel:bhgdevel .
			popd > /dev/null
			;;

	esac
done

