<?php
/**
 * Main Library Include File
 *
 * Include this file in your script to access the BHG Library.
 *
 * @access public
 * @package Roster
 * @author Adam Ashley <adam_ashley@softhome.net>
 * @copyright Copyright &copy; 2001-03 Adam Ashley, and licensed for use by 
 *            the Emperor's Hammer.
 * @version $Revision: 1.3 $
 */
 
/**
 * Include the Roster
 */
include_once('roster.inc');

/**
 * Include the Library Object
 */
include_once('library/library.inc');

/**
 * Include the Shelf Object
 */
include_once('library/shelf.inc');

/**
 * Include the Book Object
 */
include_once('library/book.inc');

/**
 * Include the Chapter Object
 */
include_once('library/chapter.inc');

/**
 * Include the Section Object
 */
include_once('library/section.inc');

/* vim: set ts=2 sw=2 fdm=marker: */

?>
