<?php
include_once 'podracer_system.inc';
include_once 'gui.inc';
include_once 'course.inc';
include_once 'owned_part.inc';
include_once 'part.inc';
include_once 'parttype.inc';
include_once 'owned_pod.inc';
include_once 'pod.inc';
include_once 'race.inc';
include_once 'race_registration.inc';
include_once 'race_result.inc';
include_once 'team.inc';
include_once 'team_member.inc';
include_once 'bet.inc';
?>
