<div><h2>Section XII: Activities</h2>
<p>Activities are the hamster that keeps the wheel turning in the BHG. Without activities available for hunters, the BHG would stagnate and become almost pointless. Throughout the years, more and more activities have been created for hunters to participate in. The following list is just a foundation of activities you can do, and the longer you remain the BHG, the more activities you’ll become involved in. These should get you started, though:
</p>
<blockquote><b><u>Kabal Authority Hunts</u></b>
<br>Even though these are called Kabal Authority Hunts, they are still available to Trainees in the Citadel. The Warden will put up specific hunts for you to do. Always available for hunters, KA Hunts usually last for a week at a time, and any number of hunts may be open. The following types of hunts are currently offered at the Kabal Authority: Crossword, Hunt the Hunter, URL Hunt, Web Hunt, What’s That?, and Who Said That?. If you don’t understand how to do one or more of the Hunts, then contact your Warden. He will be able to help you. A good fact to remember is that these are some of the easiest credits you can earn. Hunts are located on the <a href="http://ka.thebhg.org/hunts/" target="_blank">Kabal Authority website</a>.</blockquote>
<blockquote><b><u>Online Missions</u></b>
<br>These mystery-like hunts are released by the Tactician about once a month. Written by himself and/or other hunters, they require you to take clues and figure out what they mean. Your mission - what you need to find out - will be given and the account of your hunt will be told, wherein you will find the clues. At the end, you must determine what the answer to your mission is. You might be required to find information such as the bounty’s name, his location, or perhaps what weapon he used to kill someone. Online Missions vary widely, but they all fit under the same format. This activity is fun, and it tests your ability to find clues and decipher their meaning. They can be found at the <a href="http://tactician.thebhg.org/" target="_blank">Tactician's Office</a>.</blockquote>
<blockquote><b><u>Gambling</u></b>
<br>Where would bounty hunters be without gambling? There are a few ways to gamble your credits in the BHG; however, you will only learn about two ways right now. Please note that gambling will only add to or subtract from your actual Account Balance - it has no effect on your Rank Credits.
<blockquote><b><u>Boloball</u></b>
<br>Betting on certain BHG or Real Life events is what Boloball is all about. Different competitions, such as sports games or BHG activities, will be posted on there for you to bet on. Odds will be given, and you can choose who to bet for and how much you are willing to wager. Once the outcome has been decided, credits will be distributed accordingly. At the <a href="http://holonet.thebhg.org/index.php?module=boloball&page=index" target="_blank">Boloball center</a>, you can view Current Competitions as well as your current and past bets.</blockquote>
<blockquote><b><u>BHG Lotto</u></b>
<br>This is the BHG’s lottery system. Every week a number will be drawn, and those who have purchased tickets will either find themselves richer or down the money they spent on their ticket. There are three different divisions to win in, and you can either choose your numbers or have them randomly selected by the computer. An FAQ is available at the <a href="http://lawngnome.cernun.net/lotto/" target="_blank">BHG Lotto website</a> for more information, and you can also view the outcomes of past draws.</blockquote>
</blockquote>
<blockquote><b><u>Role-Playing</u></b>
<br>Role-Playing - or "RPing" - has become very popular within the BHG. A Commission position was even instituted to handle all of the RP activities on hand in the BHG. The <a href="http://overseer.thebhg.org/" target="_blank">Overseer’s Office</a> is the central source for all RP activities. Here are a few aspects of the Role-Playing side of the BHG that you should be aware of:
<blockquote><b><u>Character Sheets</u></b>
<br>If you want to do any type of RPing in the BHG, then you must first have an approved Character Sheet. If you remember in Section II when you set up your Roster page, there was also a link to Add/Edit your Character Sheet. If you want a Character Sheet, then you will need to use that to create one. Be aware, though! There are guidelines to creating a Character Sheet that you MUST abide by. The <a href="http://overseer.thebhg.org/" target="_blank">Overseer’s office</a> has everything you need to know about what is on the Character Sheet and how to fill it in. There is also a <a href="http://holonet.thebhg.org/index.php?module=library&page=book&id=33" target="_blank">Character Sheet Guide</a> in the <a href="http://holonet.thebhg.org/index.php?module=library&page=index" target="_blank">Holonet Library</a>.</blockquote>
<blockquote><b><u>Arena Matches</u></b>
<br>When two hunters want to duel it out, they take it to the Arena. Held on its designated <a href="http://boards.thebhg.org/index.php?op=topics&board=1" target="_blank">Message Board</a>, Arena Matches are text-based battles between two Hunters. They each take turns posting in a Run-On style. The number of times they may post is limited, and the locations, weapons, and degree of violence allowed in the match all vary greatly. A Hunter may challenge anyone s/he wishes, but the challenge must be accepted by the challenged Hunter in order for the match to take place. As a new member, you will probably train in the <a href="http://boards.thebhg.org/index.php?op=topics&board=27" target="_blank">Dojo of Shadows</a> until you are allowed to move on to the actual Arena. Read the <a href="http://holonet.thebhg.org/index.php?module=library&page=book&id=29" target="_blank">Arena Rules</a> and the <a href="http://holonet.thebhg.org/index.php?module=library&page=book&id=30" target="_blank">Dojo Rules</a> at the <a href="http://holonet.thebhg.org/index.php?module=library&page=index" target="_blank">Holonet Library</a>.</blockquote>
<blockquote><b><u>Run-On Stories</u></b>
<br>If you like to write fiction, then Run-On Stories will probably suit your tastes. These, like the Arena Matches, are held on a designated <a href="http://boards.thebhg.org/index.php?op=topics&board=5" target="_blank">Message Board</a>. In a Run-On [RO], a group of Hunters will take turn posting on the MB, advancing the story with each post. The goal is usually the apprehension of a bounty, but anything can happen in an RO. Your goal is to create the best story possible while keeping aware of what others are doing. Each person in the RO must have a Character Sheet, so it would be wise to use those in determining how things play out. Read the <a href="http://holonet.thebhg.org/index.php?module=library&page=book&id=26" target="_blank">Run-On Rules</a> at the <a href="http://holonet.thebhg.org/index.php?module=library&page=index" target="_blank">Holonet Library</a>.</blockquote>
</blockquote>
<p>Find out about more Activities in the <a href="http://holonet.thebhg.org/index.php?module=library&page=chapter&id=4" target="_blank">Hunter’s Manual, Chapter 5</a>, as well as other places around the BHG.
</p></div>